coverage_service: cobertura_xml
xcodeproj: PodcastsComponents/PodcastsComponents/PodcastsComponents.xcodeproj
scheme: CI_macOS
output_directory: slather_reports/CI_macOS
build_directory: /tmp/XcodeDerivedDataWithCoverage