name: CI iOS

on:
  push:
    branches: [ feature/code_coverage_codeclimate_integration ]

jobs:
  build-and-test:
    runs-on: macos-12
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Slather install
      run: sudo gem install slather
      
    - name: Build and Test
      run: xcodebuild clean build test -workspace PodcatsAppiOS/PodcatsAppiOS.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.5" ONLY_ACTIVE_ARCH=YES  -resultBundlePath CIiOSResults -derivedDataPath /tmp/XcodeDerivedDataWithCoverage

    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: CIiOSResults.xcresult
      if: success() || failure()

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: "${{ secrets.CC_TEST_REPORTER_ID }}"
      with:
        debug: true
        coverageLocations: ${{github.workspace}}/slather_reports/**/*.xml:cobertura
        coverageCommand: slather coverage -x --scheme "CI_iOS" --workspace "PodcatsAppiOS/PodcatsAppiOS.xcworkspace" --output-directory "slather_reports/CI_iOS" -b "/tmp/XcodeDerivedDataWithCoverage" "PodcatsAppiOS/PodcatsAppiOS.xcodeproj"