name: CI macOS

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-12
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.0.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    # - name: Build and Test
    #   run: xcodebuild clean build test -project PodcastsComponents/PodcastsComponents/PodcastsComponents.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES -resultBundlePath CImacOSResults
    # - uses: kishikawakatsumi/xcresulttool@v1
    #   with:
    #     path: CImacOSResults.xcresult
    #   if: success() || failure()

    - name: Install Slather
      run: gem install slather

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        debug: true
        coverageCommand: slather coverage --scheme CI_macOS --show ./PodcastsComponents/PodcastsComponents/PodcastsComponents.xcodeproj
        coverageLocations: |
          ./slather-test-output/cobertura.xml