name: CI macOS

on:
  push:
    branches: [ feature/code_coverage_codeclimate_integration ]

jobs:
  build-and-test:
    runs-on: macos-12
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.0.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Slather install
      run: sudo gem install slather
      
    - name: Build and Test
      run: xcodebuild clean build test -project PodcastsComponents/PodcastsComponents/PodcastsComponents.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES -resultBundlePath CImacOSResults -derivedDataPath /tmp/XcodeDerivedDataWithCoverage

    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: CImacOSResults.xcresult
      if: success() || failure()

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: "${{ secrets.CC_TEST_REPORTER_ID }}"
      with:
        debug: true
        coverageLocations: ${{github.workspace}}/slather_reports/**/*.xml:cobertura
        coverageCommand: slather coverage -x --scheme "CI_macOS" --output-directory "slather_reports/CI_macOS" -b "/tmp/XcodeDerivedDataWithCoverage" "PodcastsComponents/PodcastsComponents/PodcastsComponents.xcodeproj"