name: CI macOS

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-12
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Badge Action
      uses: emibcn/badge-action@v1.2.4
      label: 'Test coverage'
      status: '53.4%'
      color: 'blue,555,daf'
      path: '.github/badges/coverage.svg'

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.0.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Build and Test
      run: xcodebuild clean build test -project PodcastsComponents/PodcastsComponents/PodcastsComponents.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES -resultBundlePath CImacOSResults

    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: CImacOSResults.xcresult
      if: success() || failure()